<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrderItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_items')->delete();
        
        \DB::table('order_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => 1,
                'component_id' => 77,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => 1,
                'component_id' => 80,
                'qty' => 7,
                'unit_price' => 1,
                'total_price' => 7,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => 1,
                'component_id' => 82,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => 1,
                'component_id' => 110,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => 1,
                'component_id' => 113,
                'qty' => 13,
                'unit_price' => 1,
                'total_price' => 13,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => 1,
                'component_id' => 124,
                'qty' => 18,
                'unit_price' => 1,
                'total_price' => 18,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => 1,
                'component_id' => 134,
                'qty' => 18,
                'unit_price' => 1,
                'total_price' => 18,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:24:06',
                'updated_at' => '2024-04-02 14:24:06',
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => 2,
                'component_id' => 2,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => 2,
                'component_id' => 6,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => 2,
                'component_id' => 7,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => 2,
                'component_id' => 14,
                'qty' => 210,
                'unit_price' => 1,
                'total_price' => 210,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => 2,
                'component_id' => 16,
                'qty' => 34,
                'unit_price' => 1,
                'total_price' => 34,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => 2,
                'component_id' => 19,
                'qty' => 9,
                'unit_price' => 1,
                'total_price' => 9,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => 2,
                'component_id' => 24,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => 2,
                'component_id' => 26,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => 2,
                'component_id' => 31,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => 2,
                'component_id' => 32,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => 2,
                'component_id' => 33,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => 2,
                'component_id' => 42,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => 2,
                'component_id' => 43,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => 2,
                'component_id' => 44,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => 2,
                'component_id' => 46,
                'qty' => 14,
                'unit_price' => 1,
                'total_price' => 14,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => 2,
                'component_id' => 49,
                'qty' => 18,
                'unit_price' => 1,
                'total_price' => 18,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => 2,
                'component_id' => 56,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => 2,
                'component_id' => 58,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => 2,
                'component_id' => 41,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:31:17',
                'updated_at' => '2024-04-02 14:31:17',
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => 3,
                'component_id' => 62,
                'qty' => 232,
                'unit_price' => 1,
                'total_price' => 232,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            27 => 
            array (
                'id' => 28,
                'order_id' => 3,
                'component_id' => 67,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            28 => 
            array (
                'id' => 29,
                'order_id' => 3,
                'component_id' => 68,
                'qty' => 219,
                'unit_price' => 1,
                'total_price' => 219,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            29 => 
            array (
                'id' => 30,
                'order_id' => 3,
                'component_id' => 69,
                'qty' => 211,
                'unit_price' => 1,
                'total_price' => 211,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            30 => 
            array (
                'id' => 31,
                'order_id' => 3,
                'component_id' => 70,
                'qty' => 47,
                'unit_price' => 1,
                'total_price' => 47,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            31 => 
            array (
                'id' => 32,
                'order_id' => 3,
                'component_id' => 71,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            32 => 
            array (
                'id' => 33,
                'order_id' => 3,
                'component_id' => 73,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 14:38:44',
                'updated_at' => '2024-04-02 14:38:44',
            ),
            33 => 
            array (
                'id' => 34,
                'order_id' => 4,
                'component_id' => 124,
                'qty' => 30,
                'unit_price' => 1,
                'total_price' => 30,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:14:36',
                'updated_at' => '2024-04-02 15:14:36',
            ),
            34 => 
            array (
                'id' => 35,
                'order_id' => 4,
                'component_id' => 134,
                'qty' => 30,
                'unit_price' => 1,
                'total_price' => 30,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:14:36',
                'updated_at' => '2024-04-02 15:14:36',
            ),
            35 => 
            array (
                'id' => 36,
                'order_id' => 5,
                'component_id' => 100,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:17:55',
                'updated_at' => '2024-04-02 15:17:55',
            ),
            36 => 
            array (
                'id' => 37,
                'order_id' => 5,
                'component_id' => 102,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:17:55',
                'updated_at' => '2024-04-02 15:17:55',
            ),
            37 => 
            array (
                'id' => 38,
                'order_id' => 6,
                'component_id' => 67,
                'qty' => 209,
                'unit_price' => 1,
                'total_price' => 209,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:20:36',
                'updated_at' => '2024-04-02 15:20:36',
            ),
            38 => 
            array (
                'id' => 39,
                'order_id' => 7,
                'component_id' => 67,
                'qty' => 209,
                'unit_price' => 1,
                'total_price' => 209,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:21:59',
                'updated_at' => '2024-04-02 15:21:59',
            ),
            39 => 
            array (
                'id' => 40,
                'order_id' => 8,
                'component_id' => 85,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:24:12',
                'updated_at' => '2024-04-02 15:24:12',
            ),
            40 => 
            array (
                'id' => 41,
                'order_id' => 9,
                'component_id' => 105,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:26:49',
                'updated_at' => '2024-04-02 15:26:49',
            ),
            41 => 
            array (
                'id' => 42,
                'order_id' => 9,
                'component_id' => 110,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:26:49',
                'updated_at' => '2024-04-02 15:26:49',
            ),
            42 => 
            array (
                'id' => 43,
                'order_id' => 9,
                'component_id' => 123,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:26:49',
                'updated_at' => '2024-04-02 15:26:49',
            ),
            43 => 
            array (
                'id' => 44,
                'order_id' => 9,
                'component_id' => 133,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:26:49',
                'updated_at' => '2024-04-02 15:26:49',
            ),
            44 => 
            array (
                'id' => 45,
                'order_id' => 10,
                'component_id' => 3,
                'qty' => 12,
                'unit_price' => 1,
                'total_price' => 12,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            45 => 
            array (
                'id' => 46,
                'order_id' => 10,
                'component_id' => 22,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            46 => 
            array (
                'id' => 47,
                'order_id' => 10,
                'component_id' => 24,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            47 => 
            array (
                'id' => 48,
                'order_id' => 10,
                'component_id' => 25,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            48 => 
            array (
                'id' => 49,
                'order_id' => 10,
                'component_id' => 26,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            49 => 
            array (
                'id' => 50,
                'order_id' => 10,
                'component_id' => 32,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            50 => 
            array (
                'id' => 51,
                'order_id' => 10,
                'component_id' => 46,
                'qty' => 12,
                'unit_price' => 1,
                'total_price' => 12,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            51 => 
            array (
                'id' => 52,
                'order_id' => 10,
                'component_id' => 50,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:34:36',
                'updated_at' => '2024-04-02 15:34:36',
            ),
            52 => 
            array (
                'id' => 53,
                'order_id' => 11,
                'component_id' => 5,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            53 => 
            array (
                'id' => 54,
                'order_id' => 11,
                'component_id' => 6,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            54 => 
            array (
                'id' => 55,
                'order_id' => 11,
                'component_id' => 7,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            55 => 
            array (
                'id' => 56,
                'order_id' => 11,
                'component_id' => 8,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            56 => 
            array (
                'id' => 57,
                'order_id' => 11,
                'component_id' => 9,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            57 => 
            array (
                'id' => 58,
                'order_id' => 11,
                'component_id' => 20,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            58 => 
            array (
                'id' => 59,
                'order_id' => 11,
                'component_id' => 33,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            59 => 
            array (
                'id' => 60,
                'order_id' => 11,
                'component_id' => 60,
                'qty' => 1000,
                'unit_price' => 1,
                'total_price' => 1000,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:42:37',
                'updated_at' => '2024-04-02 15:42:37',
            ),
            60 => 
            array (
                'id' => 61,
                'order_id' => 12,
                'component_id' => 110,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:43:45',
                'updated_at' => '2024-04-02 15:43:45',
            ),
            61 => 
            array (
                'id' => 62,
                'order_id' => 13,
                'component_id' => 92,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:45:16',
                'updated_at' => '2024-04-02 15:45:16',
            ),
            62 => 
            array (
                'id' => 63,
                'order_id' => 13,
                'component_id' => 93,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:45:16',
                'updated_at' => '2024-04-02 15:45:16',
            ),
            63 => 
            array (
                'id' => 64,
                'order_id' => 14,
                'component_id' => 88,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:47:35',
                'updated_at' => '2024-04-02 15:47:35',
            ),
            64 => 
            array (
                'id' => 65,
                'order_id' => 14,
                'component_id' => 92,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:47:35',
                'updated_at' => '2024-04-02 15:47:35',
            ),
            65 => 
            array (
                'id' => 66,
                'order_id' => 14,
                'component_id' => 113,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:47:35',
                'updated_at' => '2024-04-02 15:47:35',
            ),
            66 => 
            array (
                'id' => 67,
                'order_id' => 15,
                'component_id' => 92,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:49:37',
                'updated_at' => '2024-04-02 15:49:37',
            ),
            67 => 
            array (
                'id' => 68,
                'order_id' => 15,
                'component_id' => 110,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:49:37',
                'updated_at' => '2024-04-02 15:49:37',
            ),
            68 => 
            array (
                'id' => 69,
                'order_id' => 15,
                'component_id' => 123,
                'qty' => 17,
                'unit_price' => 1,
                'total_price' => 17,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:49:37',
                'updated_at' => '2024-04-02 15:49:37',
            ),
            69 => 
            array (
                'id' => 70,
                'order_id' => 15,
                'component_id' => 133,
                'qty' => 17,
                'unit_price' => 1,
                'total_price' => 17,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:49:37',
                'updated_at' => '2024-04-02 15:49:37',
            ),
            70 => 
            array (
                'id' => 71,
                'order_id' => 16,
                'component_id' => 19,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:51:36',
                'updated_at' => '2024-04-02 15:51:36',
            ),
            71 => 
            array (
                'id' => 72,
                'order_id' => 17,
                'component_id' => 92,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-02 15:53:46',
                'updated_at' => '2024-04-02 15:53:46',
            ),
            72 => 
            array (
                'id' => 73,
                'order_id' => 18,
                'component_id' => 87,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:14:23',
                'updated_at' => '2024-04-03 05:14:23',
            ),
            73 => 
            array (
                'id' => 74,
                'order_id' => 18,
                'component_id' => 110,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:14:23',
                'updated_at' => '2024-04-03 05:14:23',
            ),
            74 => 
            array (
                'id' => 75,
                'order_id' => 19,
                'component_id' => 96,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:16:19',
                'updated_at' => '2024-04-03 05:16:19',
            ),
            75 => 
            array (
                'id' => 76,
                'order_id' => 19,
                'component_id' => 113,
                'qty' => 7,
                'unit_price' => 1,
                'total_price' => 7,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:16:19',
                'updated_at' => '2024-04-03 05:16:19',
            ),
            76 => 
            array (
                'id' => 77,
                'order_id' => 19,
                'component_id' => 27,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:16:19',
                'updated_at' => '2024-04-03 05:16:19',
            ),
            77 => 
            array (
                'id' => 78,
                'order_id' => 20,
                'component_id' => 110,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:19:30',
                'updated_at' => '2024-04-03 05:19:30',
            ),
            78 => 
            array (
                'id' => 79,
                'order_id' => 20,
                'component_id' => 123,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:19:30',
                'updated_at' => '2024-04-03 05:19:30',
            ),
            79 => 
            array (
                'id' => 80,
                'order_id' => 20,
                'component_id' => 133,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:19:30',
                'updated_at' => '2024-04-03 05:19:30',
            ),
            80 => 
            array (
                'id' => 81,
                'order_id' => 21,
                'component_id' => 19,
                'qty' => 24,
                'unit_price' => 1,
                'total_price' => 24,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            81 => 
            array (
                'id' => 82,
                'order_id' => 21,
                'component_id' => 32,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            82 => 
            array (
                'id' => 83,
                'order_id' => 21,
                'component_id' => 41,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            83 => 
            array (
                'id' => 84,
                'order_id' => 21,
                'component_id' => 42,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            84 => 
            array (
                'id' => 85,
                'order_id' => 21,
                'component_id' => 43,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            85 => 
            array (
                'id' => 86,
                'order_id' => 21,
                'component_id' => 44,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:23:39',
                'updated_at' => '2024-04-03 05:23:39',
            ),
            86 => 
            array (
                'id' => 87,
                'order_id' => 22,
                'component_id' => 78,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:27:36',
                'updated_at' => '2024-04-03 05:27:36',
            ),
            87 => 
            array (
                'id' => 88,
                'order_id' => 22,
                'component_id' => 15,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:27:36',
                'updated_at' => '2024-04-03 05:27:36',
            ),
            88 => 
            array (
                'id' => 89,
                'order_id' => 23,
                'component_id' => 110,
                'qty' => 12,
                'unit_price' => 1,
                'total_price' => 12,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:32:09',
                'updated_at' => '2024-04-03 05:32:09',
            ),
            89 => 
            array (
                'id' => 90,
                'order_id' => 23,
                'component_id' => 125,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:32:09',
                'updated_at' => '2024-04-03 05:32:09',
            ),
            90 => 
            array (
                'id' => 91,
                'order_id' => 23,
                'component_id' => 128,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:32:09',
                'updated_at' => '2024-04-03 05:32:09',
            ),
            91 => 
            array (
                'id' => 92,
                'order_id' => 24,
                'component_id' => 67,
                'qty' => 612,
                'unit_price' => 1,
                'total_price' => 612,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:37:34',
                'updated_at' => '2024-04-03 05:37:34',
            ),
            92 => 
            array (
                'id' => 93,
                'order_id' => 24,
                'component_id' => 68,
                'qty' => 209,
                'unit_price' => 1,
                'total_price' => 209,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:37:34',
                'updated_at' => '2024-04-03 05:37:34',
            ),
            93 => 
            array (
                'id' => 94,
                'order_id' => 24,
                'component_id' => 69,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:37:34',
                'updated_at' => '2024-04-03 05:37:34',
            ),
            94 => 
            array (
                'id' => 95,
                'order_id' => 25,
                'component_id' => 125,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:41:07',
                'updated_at' => '2024-04-03 05:41:07',
            ),
            95 => 
            array (
                'id' => 96,
                'order_id' => 25,
                'component_id' => 128,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:41:07',
                'updated_at' => '2024-04-03 05:41:07',
            ),
            96 => 
            array (
                'id' => 97,
                'order_id' => 25,
                'component_id' => 26,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:42:19',
                'updated_at' => '2024-04-03 05:42:19',
            ),
            97 => 
            array (
                'id' => 98,
                'order_id' => 25,
                'component_id' => 32,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:42:19',
                'updated_at' => '2024-04-03 05:42:19',
            ),
            98 => 
            array (
                'id' => 99,
                'order_id' => 26,
                'component_id' => 107,
                'qty' => 1,
                'unit_price' => 1,
                'total_price' => 1,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:44:05',
                'updated_at' => '2024-04-03 05:44:05',
            ),
            99 => 
            array (
                'id' => 100,
                'order_id' => 26,
                'component_id' => 113,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:44:05',
                'updated_at' => '2024-04-03 05:44:05',
            ),
            100 => 
            array (
                'id' => 101,
                'order_id' => 27,
                'component_id' => 87,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-03 05:44:43',
                'updated_at' => '2024-04-03 05:44:43',
            ),
            101 => 
            array (
                'id' => 102,
                'order_id' => 28,
                'component_id' => 110,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:44:59',
                'updated_at' => '2024-04-04 04:44:59',
            ),
            102 => 
            array (
                'id' => 103,
                'order_id' => 28,
                'component_id' => 123,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:44:59',
                'updated_at' => '2024-04-04 04:44:59',
            ),
            103 => 
            array (
                'id' => 104,
                'order_id' => 28,
                'component_id' => 133,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:44:59',
                'updated_at' => '2024-04-04 04:44:59',
            ),
            104 => 
            array (
                'id' => 105,
                'order_id' => 29,
                'component_id' => 92,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:46:06',
                'updated_at' => '2024-04-04 04:46:06',
            ),
            105 => 
            array (
                'id' => 106,
                'order_id' => 30,
                'component_id' => 96,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:47:07',
                'updated_at' => '2024-04-04 04:47:07',
            ),
            106 => 
            array (
                'id' => 107,
                'order_id' => 30,
                'component_id' => 122,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:47:07',
                'updated_at' => '2024-04-04 04:47:07',
            ),
            107 => 
            array (
                'id' => 108,
                'order_id' => 31,
                'component_id' => 96,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            108 => 
            array (
                'id' => 109,
                'order_id' => 31,
                'component_id' => 105,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            109 => 
            array (
                'id' => 110,
                'order_id' => 31,
                'component_id' => 110,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            110 => 
            array (
                'id' => 111,
                'order_id' => 31,
                'component_id' => 123,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            111 => 
            array (
                'id' => 112,
                'order_id' => 31,
                'component_id' => 1,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            112 => 
            array (
                'id' => 113,
                'order_id' => 31,
                'component_id' => 5,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            113 => 
            array (
                'id' => 114,
                'order_id' => 31,
                'component_id' => 24,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            114 => 
            array (
                'id' => 115,
                'order_id' => 31,
                'component_id' => 26,
                'qty' => 5,
                'unit_price' => 1,
                'total_price' => 5,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            115 => 
            array (
                'id' => 116,
                'order_id' => 31,
                'component_id' => 32,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:50:28',
                'updated_at' => '2024-04-04 04:50:28',
            ),
            116 => 
            array (
                'id' => 117,
                'order_id' => 32,
                'component_id' => 92,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:56:36',
                'updated_at' => '2024-04-04 04:56:36',
            ),
            117 => 
            array (
                'id' => 118,
                'order_id' => 33,
                'component_id' => 92,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 04:57:18',
                'updated_at' => '2024-04-04 04:57:18',
            ),
            118 => 
            array (
                'id' => 119,
                'order_id' => 34,
                'component_id' => 110,
                'qty' => 8,
                'unit_price' => 1,
                'total_price' => 8,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:00:09',
                'updated_at' => '2024-04-04 05:00:09',
            ),
            119 => 
            array (
                'id' => 120,
                'order_id' => 34,
                'component_id' => 123,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:00:09',
                'updated_at' => '2024-04-04 05:00:09',
            ),
            120 => 
            array (
                'id' => 121,
                'order_id' => 34,
                'component_id' => 133,
                'qty' => 20,
                'unit_price' => 1,
                'total_price' => 20,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:00:09',
                'updated_at' => '2024-04-04 05:00:09',
            ),
            121 => 
            array (
                'id' => 122,
                'order_id' => 35,
                'component_id' => 107,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:03:20',
                'updated_at' => '2024-04-04 05:03:20',
            ),
            122 => 
            array (
                'id' => 123,
                'order_id' => 35,
                'component_id' => 113,
                'qty' => 12,
                'unit_price' => 1,
                'total_price' => 12,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:03:20',
                'updated_at' => '2024-04-04 05:03:20',
            ),
            123 => 
            array (
                'id' => 124,
                'order_id' => 35,
                'component_id' => 24,
                'qty' => 3,
                'unit_price' => 1,
                'total_price' => 3,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:03:20',
                'updated_at' => '2024-04-04 05:03:20',
            ),
            124 => 
            array (
                'id' => 125,
                'order_id' => 35,
                'component_id' => 46,
                'qty' => 6,
                'unit_price' => 1,
                'total_price' => 6,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:03:20',
                'updated_at' => '2024-04-04 05:03:20',
            ),
            125 => 
            array (
                'id' => 126,
                'order_id' => 36,
                'component_id' => 123,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:06:22',
                'updated_at' => '2024-04-04 05:06:22',
            ),
            126 => 
            array (
                'id' => 127,
                'order_id' => 36,
                'component_id' => 133,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:06:22',
                'updated_at' => '2024-04-04 05:06:22',
            ),
            127 => 
            array (
                'id' => 128,
                'order_id' => 37,
                'component_id' => 84,
                'qty' => 10,
                'unit_price' => 1,
                'total_price' => 10,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:07:28',
                'updated_at' => '2024-04-04 05:07:28',
            ),
            128 => 
            array (
                'id' => 129,
                'order_id' => 38,
                'component_id' => 110,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:08:38',
                'updated_at' => '2024-04-04 05:08:38',
            ),
            129 => 
            array (
                'id' => 130,
                'order_id' => 39,
                'component_id' => 96,
                'qty' => 15,
                'unit_price' => 1,
                'total_price' => 15,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:10:20',
                'updated_at' => '2024-04-04 05:10:20',
            ),
            130 => 
            array (
                'id' => 131,
                'order_id' => 40,
                'component_id' => 32,
                'qty' => 4,
                'unit_price' => 1,
                'total_price' => 4,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:11:32',
                'updated_at' => '2024-04-04 05:11:32',
            ),
            131 => 
            array (
                'id' => 132,
                'order_id' => 41,
                'component_id' => 105,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:12:14',
                'updated_at' => '2024-04-04 05:12:14',
            ),
            132 => 
            array (
                'id' => 133,
                'order_id' => 41,
                'component_id' => 110,
                'qty' => 2,
                'unit_price' => 1,
                'total_price' => 2,
                'vehicle_number' => 'Stock',
                'description' => '-',
                'created_at' => '2024-04-04 05:12:14',
                'updated_at' => '2024-04-04 05:12:14',
            ),
        ));
        
        
    }
}